version: '3.1'
services:
  builder:
    build: ./build
    volumes:
      - Temp:/home/App42/target
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: 'dd'
      MYSQL_USER: 'user'
  web:
    image: tomcat:latest
    ports:
      - 8083:8080
    depends_on:
      - builder
      - db
    volumes:
      - Temp:/usr/local/tomcat/webapps
volumes:
  Temp:
