version: '3.1'
services:
  build:
    build: ./build
    volumes:
      - Temp:/home/App42PaaS-Java-MySQL-Sample/target/
      - Config:/home/HW_12/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
  web:
    image: tomcat:latest
    ports:
      - 8082:8080
    depends_on:
      - build
      - db
    volumes:
      - Temp:/usr/local/tomcat/webapps
      - Config:/usr/local/tomcat/webapps/ROOT
volumes:
  Config:
  Temp:
