version: '3.1'
services:
  builder:
    build: ./build
    volumes:
      - Temp:/home/App42PaaS-Java-MySQL-Sample/target
      - DB:/home/App42PaaS-Java-MySQL-Sample/WebContent
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      -DB:/var/lib/mysql
  web:
    image: tomcat:latest
    ports:
      - 8083:8080
    depends_on:
      - builder
      - db
    volumes:
      - Temp:/usr/local/tomcat/webapps
      - /home/HW_12/config:/usr/local/tomcat/webapps/ROOT
volumes:
  Temp:
  DB: