version: '3.1'
services:
  builder:
    build: ./build
    volumes:
      - Temp:/home/App42/target
      - Conf:/home/App42/WebContent
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - builder
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dd
      MYSQL_USER: user
  web:
    image: tomcat:7.0
    ports:
      - 8084:8080
    depends_on:
      - builder
      - db
    volumes:
      - Temp:/usr/local/tomcat/webapps
      - Conf:/usr/local/tomcat/ROOT

volumes:
  Temp:
  Conf:
