version: '3.9'
services:
  build:
    build: ./build
    volumes:
      - Temp:/home/App42PaaS-Java-MySQL-Sample/target/
      - Config:/home/App42PaaS-Java-MySQL-Sample/
  web:
    image: tomcat:latest
    ports:
      - 8082:8080
    depends_on:
      - main
      - db
    volumes:
      - Temp:/usr/local/tomcat/webapps
  db:
    image: mysql-server
    ports:
      - 8082:8080
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
       - Config:/etc/mysql/conf
volumes:
  Config:
  Temp:
